version: "3.9"

services:
  api:
    build: .
    container_name: task-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - task-net

  db:
    image: postgres:16
    container_name: task-db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task-net

  redis:
    image: redis:7
    container_name: task-redis
    ports:
      - "6379:6379"
    networks:
      - task-net

volumes:
  pgdata:

networks:
  task-net:
